#pragma once
#include <metamod/ISmmPlugin.h>
#include <metamod/sourcehook/sourcehook.h>
#include <hlsdk/public/shake.h>
#include <hlsdk/game/shared/IEffects.h>
#include <hlsdk/public/eiface.h>
#include <hlsdk/public/game/server/iplayerinfo.h>
#include <hlsdk/public/mathlib/mathlib.h>
#include <hlsdk/public/edict.h>
