#pragma once
#include "TF2/Trace/TraceHeaders.h"
#include <metamod/ISmmPlugin.h>
#include <metamod/ISmmAPI.h>
#include <metamod/sourcehook/sourcehook.h>
#include <hlsdk/public/shake.h>
#include <hlsdk/game/shared/IEffects.h>
#include <hlsdk/public/networkvar.h>
#include <hlsdk/public/eiface.h>
#include <hlsdk/public/igameevents.h>
#include <hlsdk/public/game/server/iplayerinfo.h>
#include <hlsdk/public/mathlib/mathlib.h>
#include <hlsdk/public/edict.h>
#include <hlsdk/public/tier1/convar.h>
#include <cstdlib>
#include <algorithm>
#include <cmath>
#include <string>