#pragma once

enum WaypointNodeFlagType
{
	NODE_SPAWN_RED = 1,
	NODE_SPAWN_BLUE = 2,
	NODE_ITEMFLAG_RED = 4,
	NODE_ITEMFLAG_BLUE = 8,
	NODE_HEALTH = 16,
	NODE_AMMO = 32,
	NODE_SENTRY_RED = 64,
	NODE_SENTRY_BLUE = 128
};